ALTER TABLE agi_av_kaso_abgleich_pub.differenzen 
    ALTER t_id 
        ADD GENERATED BY DEFAULT AS IDENTITY,
    ADD fehlerart_text varchar 
    
;

DROP SEQUENCE agi_av_kaso_abgleich_pub.uebersicht_des_vergleichs_t_id_seq CASCADE
;
ALTER TABLE agi_av_kaso_abgleich_pub.uebersicht_des_vergleichs
    ALTER t_id
        ADD GENERATED BY DEFAULT AS IDENTITY,
    ALTER geometrie TYPE geometry(MultiPolygon, 2056) USING ST_Multi(geometrie)
;
